/* Inline styles.css, config.js and app.js into one standalone HTML file
   that can be emailed or AirDropped for review.

   Usage: node build-single.mjs
*/
import { readFile, writeFile } from "node:fs/promises";

const OUT = "taverna-athens-review.html";

const [html, css, config, app] = await Promise.all(
  ["index.html", "styles.css", "config.js", "app.js"].map((f) => readFile(f, "utf8"))
);

// a literal </style> or </script> inside the inlined text would end the
// element early, so neutralise them
const forStyle = (s) => s.replace(/<\/style>/gi, () => "<\\/style>");
const forScript = (s) => s.replace(/<\/script>/gi, () => "<\\/script>");

/* Every replacement below passes a function rather than a string. With a
   string, replace() interprets $$, $&, $` and $' inside it — and app.js
   defines a $$ helper, which would silently collapse into $ and redefine
   the single-element selector as the query-all one. */
const sub = (haystack, needle, replacement) => {
  if (!haystack.includes(needle)) throw new Error(`not found in index.html: ${needle}`);
  return haystack.replace(needle, () => replacement);
};

let out = html;

out = sub(out, '<link rel="stylesheet" href="styles.css">', `<style>\n${forStyle(css)}\n</style>`);

out = sub(
  out,
  '<script src="config.js" defer></script>\n<script src="app.js" defer></script>',
  `<script>\n${forScript(config)}\n</script>\n<script>\n${forScript(app)}\n</script>`
);

// leave a note in the source for whoever opens this in an editor
out = sub(
  out,
  "<head>",
  `<head>
<!-- Standalone review build of TAVERNA TAKE OVER. Generated by
     build-single.mjs from index.html + styles.css + config.js + app.js.
     Edit those files, not this one. Fonts load from Google Fonts, so a
     connection gives the intended typography; offline it falls back. -->`
);

for (const leftover of ['href="styles.css"', 'src="config.js"', 'src="app.js"']) {
  if (out.includes(leftover)) throw new Error(`failed to inline: ${leftover}`);
}

// guard against the replacement text being mangled on the way in
for (const marker of ["function $$(", "window.SITE_CONFIG", "--meander-gold:"]) {
  if (!out.includes(marker)) throw new Error(`inlined content was corrupted, missing: ${marker}`);
}
const countIn = (s, m) => s.split(m).length - 1;
for (const [label, src, marker] of [
  ["app.js", app, "$$("],
  ["styles.css", css, "url(\"data:image/svg+xml,"],
]) {
  if (countIn(out, marker) !== countIn(src, marker)) {
    throw new Error(`${label}: occurrences of ${marker} changed during inlining`);
  }
}

await writeFile(OUT, out, "utf8");
console.log(`${OUT} — ${(Buffer.byteLength(out) / 1024).toFixed(0)} KB, fully standalone`);
